### ISSUE TITLE
DHT22 returning value of 0

### ISSUE THREAD

**Issue by pedalpete** [Vuzi/raspi-sensors#5]
I've just tried this package with an RHT03 (apparently the same as a DHT22 from all the documentation I can find.

The response I get from the chip is 

```
 { type: 'Temperature',
  unit: 'Degree Celsius',
  unit_display: 'Â°C',
  value: 0,
  date: Thu Apr 21 2016 10:51:01 GMT+0000 (UTC),
  timestamp: 1461235861664,
  sensor_name: 'undefined',
  sensor_type: 'DHT22' }
```

I've checked the provided address (pin 4 in my case) is correct by changing trying a different pin number, which does not return a response at all. 

I also see sensor name is undefined. Does that look correct to you? Not sure what sort of debugging can really be done here, but thought I'd see if this is something you've come up against before.

**Comment by Vuzi** [comment]
Did you try to use (with success ?) the sensor with another software, like in Python to see if the sensor works properly ?

**Comment by pedalpete** [comment]
I've just tried using the sensor with the Adafruit DHT22 library, and it looks like that is failing as well. Must be a problem with the sensor. Sorry to bother you with that.

**Comment by Vuzi** [comment]
No worries, good luck with your sensor!
